### ISSUE TITLE
Uninitialized variables in Eab2DFT

### ISSUE THREAD

**Issue by susilehtola** [susilehtola/x2dhf#2]
The lines 77, 78, 83 and 84 in https://github.com/susilehtola/x2dhf/blob/master/src/Eab2DFT.f90#L77 use variables ipc1 and ipc2 that aren't initialized. @jacekkobus

**Comment by jacekkobus** [comment]
Fixed.

**Comment by susilehtola** [comment]
I'm still getting
```
/home/work/x2dhf/src/Eab2DFT.f90:72:0:

     call prod2 (isiorb2,psi(iborb2),excp(length-mxsize),wk1)
 
Warning: ‘length’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/work/x2dhf/src/Eab2DFT.f90:87:0:

     engo(ipc12)=sflagra*((1.0_PREC-dflagra)*engo1+dflagra*engoprv1)
 
Warning: ‘engo1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/work/x2dhf/src/Eab2DFT.f90:87:0: Warning: ‘engoprv1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/home/work/x2dhf/src/Eab2DFT.f90:88:0:

     engo(ipc21)=sflagra*((1.0_PREC-dflagra)*engo2+dflagra*engoprv2)
 
Warning: ‘engo2’ may be used uninitialized in this function [-Wmaybe-uninitialized]
```
and don't see engo1 and engo2 getting initialized anywhere..
